# Generated by Django 4.1.3 on 2022-11-03 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperDensity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaperFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaperHeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaperKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('p_density', models.ManyToManyField(to='Product.paperdensity')),
            ],
        ),
        migrations.CreateModel(
            name='PaperWidth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='Замовлення/%Y/%m/%d/')),
                ('is_moved', models.BooleanField(default=True)),
                ('p_density', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.paperdensity')),
                ('p_format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.paperformat')),
                ('p_height', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.paperheight')),
                ('p_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.paperkind')),
                ('p_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.papertype')),
                ('p_width', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.paperwidth')),
            ],
        ),
    ]
